version: '3.9'
services:
  frontend:
    container_name: frontend
    build:
      context: . #if your Dockerfile is not at the same level change the path here (./frontend)
      target: runner
      dockerfile: Dockerfile
#    restart: always
    command: yarn dev
    volumes:
      - .:/app
      - ./node_modules
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      FRONTEND_BUILD: ${FRONTEND_BUILD}
      PORT: 3000
    networks:
      - chat_businees_app_network
networks:
  chat_businees_app_network:
    driver: bridge
